In [18]:
from transformers import AutoTokenizer, ElectraForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("beomi/KcELECTRA-base")
model = ElectraForSequenceClassification.from_pretrained("beomi/KcELECTRA-base", num_labels = 6,)

Some weights of the model checkpoint at beomi/KcELECTRA-base were not used when initializing ElectraForSequenceClassification: ['discriminator_predictions.dense_prediction.bias', 'discriminator_predictions.dense.bias', 'discriminator_predictions.dense_prediction.weight', 'discriminator_predictions.dense.weight']
- This IS expected if you are initializing ElectraForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing ElectraForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of ElectraForSequenceClassification were not initialized from the model checkpoint at beomi/KcELECTRA-base and are newly initialized: ['classifier.dense.weight', 'classifier.

In [3]:
tokenizer.add_tokens(['빂', '칻', '뿨' ,'ᆢ', '탆', '믱', '👌' , '☼' ,'｀', '뵛' ,'굠', '큩', '훃' ,'즠'])
tokenizer.tokenize('믱 ;ㅁ; 시간이 없어서 시도도 사실 못해봐서...')

['믱',
 ';',
 'ㅁ',
 ';',
 '시간이',
 '없어서',
 '시도',
 '##도',
 '사실',
 '못해',
 '##봐서',
 '.',
 '.',
 '.']

In [15]:
len(tokenizer.vocab.values())
# tokenizer.vocab.keys()

50149

In [20]:
model.config

ElectraConfig {
  "_name_or_path": "beomi/KcELECTRA-base",
  "architectures": [
    "ElectraForPreTraining"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "embedding_size": 768,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2",
    "3": "LABEL_3",
    "4": "LABEL_4",
    "5": "LABEL_5"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2,
    "LABEL_3": 3,
    "LABEL_4": 4,
    "LABEL_5": 5
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "electra",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "summary_activation": "gelu",
  "summary_last_dropout": 0.1,
  "summary_type": "first",
  "summary_use_proj": true,
  "tokenizer_class": "BertTokenizer",
  "transformers_version": "4.

In [21]:
import torch
from transformers import ElectraTokenizer, ElectraForSequenceClassification

tokenizer = ElectraTokenizer.from_pretrained("bhadresh-savani/electra-base-emotion")
model = ElectraForSequenceClassification.from_pretrained("bhadresh-savani/electra-base-emotion")

inputs = tokenizer("Hello, my dog is ugly af", return_tensors="pt")

with torch.no_grad():
    logits = model(**inputs).logits

predicted_class_id = logits.argmax().item()
model.config.id2label[predicted_class_id]

'joy'

In [25]:
inputs = tokenizer("Hello, my dog is angryy", return_tensors="pt")

with torch.no_grad():
    logits = model(**inputs).logits

predicted_class_id = logits.argmax().item()
model.config.id2label[predicted_class_id]

'anger'

In [49]:
torch.nn.functional.one_hot(torch.tensor(5), num_classes = 6)

tensor([0, 0, 0, 0, 0, 1])

In [56]:
# Example of target with class indices
from torch import nn
from torch.nn import functional as F
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input, target)
output.backward()
# Example of target with class probabilities
# input = torch.randn(3, 5, requires_grad=True)
# target = torch.randn(3, 5).softmax(dim=1)
# output = loss(input, target)
# output.backward()

In [59]:
t = torch.tensor([5])
t = t.int()
F.one_hot(torch.tensor(5), num_classes = 6)



tensor([0, 0, 0, 0, 0, 1])

In [63]:
y = torch.tensor([
                [3],
                [4],
                [1],
                [5],
                [0],
                  ])
y

tensor([[3],
        [4],
        [1],
        [5],
        [0]])

In [64]:
F.one_hot(y, num_classes=6)

tensor([[[0, 0, 0, 1, 0, 0]],

        [[0, 0, 0, 0, 1, 0]],

        [[0, 1, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 1]],

        [[1, 0, 0, 0, 0, 0]]])

In [65]:
predictions = torch.rand(2, 3, 4)
target = torch.randint(4, (2, 3))

# Reorder the dimensions
# From: [time_step, batch_size, vocabulary_size]
# To: [batch_size, vocabulary_size, time_step]
predictions = predictions.permute(1, 2, 0)
# From: [time_step, batch_size]
# To: [batch_size, time_step]
target = target.transpose(0, 1)

F.cross_entropy(predictions, target)

tensor(1.4559)

In [85]:
x = torch.rand(32,1)
x.squeeze(dim=-1)

tensor([0.6010, 0.2821, 0.3351, 0.9137, 0.1850, 0.3344, 0.0952, 0.1471, 0.0446,
        0.9399, 0.7119, 0.9475, 0.9432, 0.9210, 0.3419, 0.9713, 0.8823, 0.8382,
        0.1088, 0.5653, 0.8375, 0.5046, 0.2682, 0.5888, 0.3263, 0.1629, 0.3239,
        0.4608, 0.2698, 0.1619, 0.4669, 0.9729])

In [86]:
# Example of target with class indices
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input, target)
output.backward()


In [96]:
input

tensor([[-1.0920, -0.0515, -0.2608,  1.1424,  1.1313],
        [-1.6017,  0.5182,  1.3991, -2.1566, -0.8373],
        [ 0.3238, -0.9305, -0.6168, -1.3069, -0.5969]], requires_grad=True)

In [98]:
input.argmax(dim=1).float()

tensor([3., 2., 0.])

In [104]:
import argparse
import os
import re
import emoji
import random
import numpy as np
from pytorch_lightning.callbacks.early_stopping import EarlyStopping

import pandas as pd

from tqdm.auto import tqdm

import transformers
import torch
import torchmetrics
import pytorch_lightning as pl
from torch.nn import functional as F

from pytorch_lightning.loggers import WandbLogger
from pytorch_lightning.callbacks import ModelCheckpoint
from pytorch_lightning.callbacks import LearningRateMonitor

from soynlp.normalizer import repeat_normalize

import dill

import wandb

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


In [105]:
class Model(pl.LightningModule):
    def __init__(
        self,
        model_name,
        lr,
        max_epoch,
        warmup_ratio,
        gradient_accumulation_steps,
        tokenizer,
    ):
        super().__init__()
        self.save_hyperparameters()

        self.model_name = model_name
        self.lr = lr
        self.max_epoch = max_epoch
        self.warmup_ratio = warmup_ratio
        self.gradient_accumulation_steps = gradient_accumulation_steps

        # 사용할 모델을 호출합니다.
        self.plm = transformers.AutoModelForSequenceClassification.from_pretrained(
            pretrained_model_name_or_path=model_name, num_labels=6
        )
        self.plm.resize_token_embeddings(len(tokenizer))

        self.loss_func = torch.nn.CrossEntropyLoss()

    def forward(self, x):
        x = self.plm(x)["logits"]

        return x

    def training_step(self, batch, batch_idx):
        x, y = batch
        logits = self(x)
        loss = self.loss_func(logits, y.type(torch.LongTensor).squeeze().cuda())
        self.log("train_loss", loss)

        return loss

    def validation_step(self, batch, batch_idx):
        x, y = batch
    
        logits = self(x)
        loss = self.loss_func(logits, y.type(torch.LongTensor).squeeze().cuda())
        self.log("val_loss", loss)
        self.log(
            "val_pearson",
            torchmetrics.functional.pearson_corrcoef(logits.argmax(dim=1).float().squeeze(), y.float().squeeze()),
        )

        return loss

    def test_step(self, batch, batch_idx):
        x, y = batch
        logits = self(x)

        self.log(
            "test_pearson",
            torchmetrics.functional.pearson_corrcoef(logits.argmax(dim=1).float().squeeze(), y.float().squeeze()),
        )

    def predict_step(self, batch, batch_idx):
        x = batch
        logits = self(x)

        return logits.squeeze()

    def configure_optimizers(self):
        total_steps = (
            len(self.trainer.datamodule.train_dataloader())
            // self.gradient_accumulation_steps
            * self.max_epoch
        )
        optimizer = torch.optim.AdamW(self.parameters(), lr=self.lr)
        scheduler = transformers.get_linear_schedule_with_warmup(
            optimizer=optimizer,
            num_warmup_steps=int(total_steps * self.warmup_ratio),
            num_training_steps=total_steps,
        )

        optimizer_config = {
            "optimizer": optimizer,
            "lr_scheduler": {
                "scheduler": scheduler,
                "interval": "step",
                "frequency": 1,
            },
        }

        return optimizer_config

In [113]:
model = torch.load("base_model.pt")
model.eval()

RuntimeError: PytorchStreamReader failed locating file data.pkl: file not found